import { test, expect } from '@playwright/test';
import sharp from 'sharp';
import { mockCorrections } from '../helpers/correction-ui';
import { correctionStrings } from '../../lib/correction-strings';
import { profileReviewStrings } from '../../lib/profile-review-strings';

for (const field of ['first_name', 'bio'] as const) {
  test(`${field} only opens its editor, preserves failed saves and requires explicit submission`, async ({ context, page }) => {
    const fixture = await mockCorrections(context, [field]);
    await page.goto('/profile?edit=1');
    const flow = page.getByTestId('focused-corrections');
    await expect(flow.getByRole('heading', { name: correctionStrings.en.titles[field] })).toBeVisible();
    await expect(flow.getByRole('textbox')).toHaveCount(1);
    await expect(flow).toContainText('Profile not yet approved');
    await expect(flow).toContainText(profileReviewStrings.en.reasons.misleading_identity);
    const input = flow.getByRole('textbox');
    await input.fill(field === 'first_name' ? 'Alix' : 'My revised bio');
    fixture.faults.save = true;
    await flow.getByRole('button', { name: correctionStrings.en.save[field], exact: true }).click();
    await expect(flow.getByRole('alert')).toContainText('Your entry is still here');
    await expect(input).toHaveValue(field === 'first_name' ? 'Alix' : 'My revised bio');
    expect(fixture.state.updatedFields).toEqual([]);
    fixture.faults.save = false; fixture.faults.loseSave = true;
    await flow.getByRole('button', { name: 'Try again', exact: true }).click();
    await expect(flow.getByRole('heading', { name: 'Ready to send' })).toBeVisible();
    expect(fixture.commands.saves[0].p_request_id).toBe(fixture.commands.saves[1].p_request_id);
    expect(fixture.commands.submissions).toBe(0);
    await page.reload();
    await expect(flow.getByRole('heading', { name: 'Ready to send' })).toBeVisible();
    await expect(flow).toContainText('has not been submitted');
    fixture.faults.submit = true;
    await flow.getByRole('button', { name: 'Send for review' }).click();
    await expect(flow.getByRole('alert')).toBeVisible();
    await expect(flow.getByRole('heading', { name: 'Ready to send' })).toBeVisible();
    fixture.faults.submit = false; fixture.faults.loseSubmit = true;
    await flow.getByRole('button', { name: 'Send for review' }).dblclick();
    await expect(flow).toContainText('Awaiting approval');
    await expect(flow.getByRole('alert')).toHaveCount(0);
    expect(fixture.commands.submissions).toBe(2);
    expect(fixture.commands.acknowledgements).toBe(1);
    await page.reload(); await expect(flow).toContainText('Awaiting approval');
    await flow.getByRole('button', { name: 'Account settings' }).click();
    await expect(page.getByRole('heading', { name: 'Edit my profile' })).toBeVisible();
  });
}

test('multiple corrections resume partial progress, revisit saved values and recover replacement failure', async ({ context, page }) => {
  const fixture = await mockCorrections(context, ['first_name', 'bio']);
  await page.goto('/profile?edit=1');
  const flow = page.getByTestId('focused-corrections');
  await expect(flow).toContainText('1 of 2');
  await flow.getByRole('textbox').fill('Alix');
  await flow.getByRole('button', { name: 'Save & continue' }).click();
  await expect(flow).toContainText('2 of 2');
  expect(fixture.commands.submissions).toBe(0);
  await page.reload(); await expect(flow).toContainText('2 of 2');
  await flow.getByRole('button', { name: 'Previous change' }).click();
  await expect(flow.getByRole('textbox')).toHaveValue('Alix');
  expect(fixture.commands.cancellations).toBe(0);
  await flow.getByRole('textbox').fill('Alex');
  fixture.faults.save = true;
  await flow.getByRole('button', { name: 'Save & continue' }).click();
  await expect(flow.getByRole('alert')).toBeVisible();
  await expect(flow.getByRole('textbox')).toHaveValue('Alex');
  fixture.faults.save = false;
  await flow.getByRole('button', { name: 'Try again' }).click();
  await expect(flow).toContainText('2 of 2');
  await flow.getByRole('textbox').fill('A revised bio');
  await flow.getByRole('button', { name: 'Save bio', exact: true }).click();
  await expect(flow.getByRole('heading', { name: 'Ready to send' })).toBeVisible();
  await expect(flow).toContainText('Alex'); await expect(flow).toContainText('A revised bio');
  await flow.getByRole('button', { name: 'Edit First name' }).click();
  await expect(flow.getByRole('textbox')).toHaveValue('Alex');
  await flow.getByRole('button', { name: 'Save first name' }).click();
  await expect(flow.getByRole('heading', { name: 'Ready to send' })).toBeVisible();
  expect(fixture.commands.cancellations).toBe(1);
  expect(fixture.commands.submissions).toBe(0);
});

test('photo-only correction uses the real crop pipeline and retains the selected photo after failed upload', async ({ context, page }) => {
  const fixture = await mockCorrections(context, ['photo']);
  await page.goto('/profile?edit=1');
  const flow = page.getByTestId('focused-corrections');
  await expect(flow.getByRole('heading', { name: correctionStrings.en.titles.photo })).toBeVisible();
  await expect(flow.getByRole('textbox')).toHaveCount(0);
  await expect(flow.getByRole('button', { name: 'Save photo', exact: true })).toBeDisabled();
  const image = await sharp({ create: { width: 600, height: 800, channels: 3, background: '#805347' } }).jpeg().toBuffer();
  await flow.locator('input[type=file]').setInputFiles({ name: 'correction.jpg', mimeType: 'image/jpeg', buffer: image });
  const crop = page.getByRole('dialog');
  await crop.getByRole('button', { name: 'Confirm crop' }).click();
  await expect(flow.locator('img')).toBeVisible();
  fixture.faults.upload = true;
  await flow.getByRole('button', { name: 'Save photo', exact: true }).click();
  await expect(flow.getByRole('alert')).toContainText('upload');
  await expect(flow.locator('img')).toBeVisible();
  await flow.getByRole('combobox').selectOption('fr');
  await expect(flow.getByRole('alert')).not.toContainText('upload');
  await expect(flow.locator('img')).toBeVisible();
  await flow.getByRole('combobox').selectOption('en');
  expect(fixture.state.updatedFields).toEqual([]);
  fixture.faults.upload = false;
  await flow.getByRole('button', { name: 'Try again', exact: true }).click();
  await expect(flow.getByRole('heading', { name: 'Ready to send' })).toBeVisible();
  expect(fixture.commands.uploads).toBe(2); expect(fixture.commands.submissions).toBe(0);
});

for (const locale of ['en', 'fr', 'es'] as const) {
  test(`focused mobile states match the reference in ${locale}, including long text and language changes`, async ({ context, page }) => {
    await mockCorrections(context, ['first_name', 'bio', 'photo']);
    await page.setViewportSize({ width: 320, height: 740 });
    await page.goto('/profile?edit=1');
    const flow = page.getByTestId('focused-corrections');
    await flow.getByRole('combobox').selectOption(locale);
    const s = correctionStrings[locale];
    await flow.getByRole('textbox').fill('Alix');
    await flow.getByRole('combobox').selectOption(locale === 'en' ? 'fr' : 'en');
    await expect(flow.getByRole('textbox')).toHaveValue('Alix');
    await flow.getByRole('combobox').selectOption(locale);
    await page.screenshot({ path: test.info().outputPath(`correction-${locale}-name.png`), fullPage: true });
    await flow.getByRole('button', { name: s.next, exact: true }).click();
    await flow.getByRole('textbox').fill('A longer bio with words that wrap cleanly on a narrow mobile screen.');
    await page.screenshot({ path: test.info().outputPath(`correction-${locale}-bio.png`), fullPage: true });
    await flow.getByRole('button', { name: s.next, exact: true }).click();
    await expect(flow.getByRole('heading', { name: s.titles.photo })).toBeVisible();
    await expect(flow).toHaveAttribute('aria-busy', 'false');
    await page.screenshot({ path: test.info().outputPath(`correction-${locale}-photo.png`), fullPage: true });
    const image = await sharp({ create: { width: 600, height: 800, channels: 3, background: '#805347' } }).jpeg().toBuffer();
    await flow.locator('input[type=file]').setInputFiles({ name: 'photo.jpg', mimeType: 'image/jpeg', buffer: image });
    await page.getByRole('dialog').getByRole('button', { name: ({ en: 'Confirm crop', fr: 'Valider le cadrage', es: 'Confirmar encuadre' })[locale] }).click();
    await flow.getByRole('button', { name: s.save.photo, exact: true }).click();
    await expect(flow.getByRole('heading', { name: s.ready })).toBeVisible();
    await page.screenshot({ path: test.info().outputPath(`correction-${locale}-ready.png`), fullPage: true });
    await flow.getByRole('button', { name: s.submit, exact: true }).click();
    await expect(flow).toContainText(s.waiting);
    await page.screenshot({ path: test.info().outputPath(`correction-${locale}-awaiting.png`), fullPage: true });
    await expect(page.locator('body')).toHaveJSProperty('scrollWidth', 320);
    const primary = flow.getByRole('button', { name: s.submit, exact: true }); await expect(primary).toHaveCount(0);
  });
}

test('late correction reads, Unicode limits and empty bio do not discard drafts or enable unconfirmed progress', async ({ context, page }) => {
  const fixture = await mockCorrections(context, ['bio']);
  fixture.faults.read = true;
  await page.goto('/profile?edit=1');
  const flow = page.getByTestId('focused-corrections');
  await expect(flow.getByRole('textbox')).toBeDisabled();
  fixture.faults.read = false; await flow.getByRole('button', { name: 'Try again' }).click();
  await flow.getByRole('textbox').fill('😀'.repeat(300));
  await expect(flow).toContainText('300 / 300');
  await expect(flow.getByRole('button', { name: 'Save bio', exact: true })).toBeEnabled();
  await flow.getByRole('textbox').fill('😀'.repeat(301));
  await expect(flow.getByRole('button', { name: 'Save bio', exact: true })).toBeDisabled();
  await flow.getByRole('textbox').fill('');
  await flow.getByRole('button', { name: 'Save bio', exact: true }).click();
  await expect(flow).toContainText('Bio removed');
  expect(fixture.commands.submissions).toBe(0);
});

test('legacy field links and short mobile keyboard navigation open only requested corrections', async ({ context, page }) => {
  const fixture = await mockCorrections(context, ['first_name']);
  await page.setViewportSize({ width: 320, height: 390 });
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await page.goto('/profile?edit=1#profile-review-bio');
  const flow = page.getByTestId('focused-corrections');
  await expect(flow.getByRole('heading', { name: correctionStrings.en.titles.first_name })).toBeFocused();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.keyboard.press('Tab');
  const name = flow.getByRole('textbox', { name: 'First name', exact: true });
  await expect(name).toBeFocused();
  await name.fill('😀'.repeat(31));
  await expect(flow.getByRole('button', { name: 'Save first name' })).toBeDisabled();
  await name.fill('😀'.repeat(30));
  await expect(flow).toContainText('30 / 30');
  await name.press('Enter');
  await expect(flow.getByRole('heading', { name: 'Ready to send' })).toBeFocused();
  await flow.getByRole('button', { name: 'Edit First name' }).click();
  await expect(name).toHaveValue('😀'.repeat(30));
  await flow.getByRole('button', { name: 'Account settings' }).click();
  await page.goBack();
  await expect(flow).toBeVisible();
  await expect(name).toHaveValue('😀'.repeat(30));
  expect(fixture.commands.submissions).toBe(0);
});

test('a delayed or failed initial moderation read cannot open the legacy name dialog or unrelated editors', async ({ context, page }) => {
  const fixture = await mockCorrections(context, ['first_name']);
  let release: () => void = () => {};
  const held = new Promise<void>(resolve => { release = resolve; });
  let fail = true;
  let approved = false;
  await context.route('**/rest/v1/rpc/my_profile_review', async route => {
    await held;
    return route.fulfill(fail ? { status: 503, json: { message: 'Unavailable' } } : { json: approved ? null : fixture.state });
  });
  await page.goto('/profile?edit=1#profile-review-first_name');
  await expect(page.getByRole('status')).toContainText('Loading your saved changes');
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await expect(page.getByRole('textbox')).toHaveCount(0);
  release();
  await expect(page.getByRole('main').getByRole('alert')).toBeVisible();
  await expect(page.getByRole('button', { name: 'Account settings' })).toBeVisible();
  fail = false;
  await page.getByRole('button', { name: 'Refresh', exact: true }).click();
  await expect(page.getByTestId('focused-corrections').getByRole('heading', { name: correctionStrings.en.titles.first_name })).toBeVisible();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await expect(page.getByRole('textbox')).toHaveCount(1);
  approved = true;
  await page.evaluate(() => window.dispatchEvent(new Event('amourette-participant-refresh')));
  await expect(page.getByTestId('focused-corrections')).toHaveCount(0);
  await expect(page.getByRole('heading', { name: 'Edit my profile' })).toBeVisible();
  await expect(page.getByRole('dialog')).toHaveCount(0);
});

test('a requested bio deep link opens its focused editor in a multiple-field cycle', async ({ context, page }) => {
  await mockCorrections(context, ['first_name', 'bio']);
  await page.goto('/profile?edit=1#profile-review-bio');
  const flow = page.getByTestId('focused-corrections');
  await expect(flow.getByRole('textbox', { name: 'Bio', exact: true })).toBeVisible();
  await expect(flow).toContainText('2 of 2');
  await expect(flow.getByRole('textbox')).toHaveCount(1);
});
