import { readFile, writeFile } from 'node:fs/promises';

const root = 'docs/brand/explorations/logo-wordmark/integration-preview';
const deployed = process.argv[2] === 'preview';
const before = JSON.parse(await readFile(`${root}/${deployed ? 'aligned' : 'after'}.json`, 'utf8'));
const after = JSON.parse(await readFile(`${root}/${deployed ? 'preview' : 'aligned'}.json`, 'utf8'));
const titles = {
  'home-new': 'Welcome · first visit', 'home-returning': deployed ? 'Welcome back · profile' : 'Welcome back · profile and conversation',
  room: 'Live room · long venue and profile names', 'room-menu': 'Live room · open menu',
  'room-hint': 'First-entry reminder', 'email-prompt': 'Room email invitation',
  waiting: 'Pre-launch waiting room', entry: 'Arrival threshold', 'profile-edit': 'Edit profile',
  age: 'Age confirmation', match: 'Mutual match reveal', email: 'Email preferences',
  admin: 'Admin sign-in', reset: 'Admin password recovery · invalid link',
  'home-loading': 'Public loading', 'home-error': 'Public error',
  'room-loading': 'Venue standby', 'room-error': 'Venue error', closed: 'Outside opening hours',
  ended: 'Night ended', left: 'Presence ended', onboarding: 'Onboarding · unchanged',
  unsubscribe: deployed ? 'Web unsubscribe · invalid link' : 'Web unsubscribe · service unavailable',
};
const cards = after.map(row => {
  const prior = before.find(item => item.name === row.name && item.width === row.width);
  if (!prior) throw new Error(`Missing baseline for ${row.name} ${row.width}`);
  return `<article data-width="${row.width}" data-state="${row.name}">
    <header><h2>${titles[row.name]}</h2><p>${row.path.replaceAll('&', '&amp;')} · ${row.width} × ${row.height} viewport · simulated state</p></header>
    <div class="pair">${[[prior, deployed ? 'Before · approved alignment' : 'Before · first integration'], [row, deployed ? 'After · Vercel with current main' : 'After · artwork aligned']].map(([capture, label]) => `<figure><figcaption>${label}</figcaption><a href="captures/${capture.file}" target="_blank" rel="noopener" aria-label="Open ${label} screenshot: ${titles[row.name]}"><img src="captures/${capture.file}" alt="${titles[row.name]} — ${label}" loading="lazy" width="${row.width}"></a></figure>`).join('')}</div>
  </article>`;
}).join('\n');
await writeFile(`${root}/${deployed ? 'deployed' : 'index'}.html`, `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Amourette · app integration review</title>
<style>
*{box-sizing:border-box}body{margin:0;background:#eee9e4;color:#21161a;font:16px/1.5 system-ui,sans-serif}main{max-width:1500px;margin:auto;padding:32px 24px}h1{font-size:clamp(28px,4vw,48px);line-height:1.1;max-width:850px;margin:12px 0 20px}h2{font-size:21px;margin:0}p{max-width:900px}.eyebrow{letter-spacing:.15em;text-transform:uppercase;font-size:12px}.intro{border-bottom:1px solid #b9acae;padding-bottom:24px}.note{border-left:3px solid #a51330;padding-left:16px}nav{position:sticky;top:0;z-index:2;background:#eee9e4f5;display:flex;flex-wrap:wrap;gap:12px;padding:16px 0;border-bottom:1px solid #b9acae}label{display:flex;align-items:center;gap:8px}select{padding:8px;border:1px solid #b9acae;border-radius:5px;background:white;font:inherit}article{margin:40px 0 64px;scroll-margin-top:100px}article header p{font-size:13px;color:#64535a;margin:6px 0 18px}.pair{display:grid;grid-template-columns:1fr 1fr;gap:24px;align-items:start}figure{margin:0;background:#e0d7d2;padding:16px;min-width:0;text-align:center}figcaption{font-size:13px;margin-bottom:12px}figure img{display:block;max-width:100%;height:auto;margin:auto;box-shadow:0 4px 18px #21161a20}a{color:inherit}figure a{display:block}.icons{display:flex;flex-wrap:wrap;align-items:center;gap:24px;padding:24px;background:#120a0f;color:#efe6e0}.icons figure{background:transparent}.icons img{box-shadow:none}.icons figcaption{margin-top:12px}.hidden{display:none}footer{padding:24px 0;font-size:13px}@media(max-width:600px){main{padding:24px 12px}.pair{gap:8px}figure{padding:6px}figcaption{font-size:11px}}
</style></head><body><main>
<div class="intro"><p class="eyebrow">Issue #39 · ${deployed ? 'deployed review' : 'local review'} · September 8, 2026</p><h1>${deployed ? 'The final application on Vercel.' : 'The logo aligned with the page.'}</h1>
${deployed ? '<p>The approved alignment is on the left; the current deployed application is on the right. Upstream corrections remove chat links from the returning landing and the duplicate logo from the first-entry reminder. Other logo placements retain the approved treatment. <a href="index.html">Open the alignment review</a>.</p>' : `<p>Updated comparison: the first integration is on the left, the aligned implementation on the right. The visible A now starts with the adjacent venue name or heading on left-aligned screens. The complete SVG moves about 15px into the gutter at its 192px width; no artwork, clear space, size or adjacent text is changed. Centered compositions keep their axis. <a href="initial.html">Open the original checkpoint comparison</a>.</p>`}
<p class="note"><strong>Every personal and venue state is simulated.</strong> Profiles, illustrated portraits, venue, attendance and matches are synthetic. ${deployed ? 'Application assets are served by Vercel. Browser Supabase calls and WebSockets are intercepted; no personal data is fetched or written. The server-side unsubscribe token check is read-only. Vercel’s review toolbar is excluded.' : 'Browser requests are intercepted against a fictitious Supabase hostname; no shared database is accessed.'} The match is revealed through the real tap handler with a mocked response. ${deployed ? 'Unsubscribe shows the actual invalid-link state without a token.' : 'Unsubscribe shows a simulated service failure.'} The room email invitation uses an accelerated test clock to reach the existing two-minute prompt. These are screenshots, not an interactive app preview.</p>
<p>Captures use Chromium, English, 100% zoom and reduced motion for repeatability. Full-page images retain scrollable content; the listed height is the viewport, not necessarily the image height. At 320px, profile and age headers wrap the language control to preserve the 192px whole-file minimum. Existing display typography and onboarding remain unchanged.</p>
<p><strong>Status:</strong> alignment preview approved; final PR delivery authorized. Physical phone/browser shortcut checks remain pending. ${deployed ? 'This gallery records agent inspection of the deployed application, not founder approval of a new design or a physical-device test.' : 'This gallery records the pre-delivery visual review. <a href="deployed.html">See the final deployed application</a>.'}</p></div>
<nav aria-label="Gallery filters"><label>Viewport <select id="width"><option value="390">Mobile · 390 px</option><option value="320">Narrow mobile · 320 px</option><option value="1280">Desktop · 1280 px</option><option value="all">All sizes</option></select></label><label>Screen <select id="state"><option value="all">All screens</option>${Object.entries(titles).map(([key, title]) => `<option value="${key}">${title}</option>`).join('')}</select></label><span id="count" aria-live="polite"></span></nav>
${cards}
<section><h2>Browser and phone icon assets</h2><p>F1 is served as the browser SVG/ICO. B1 is served as the 180px Apple touch icon. Platform masks are supplied by the phone. No web app manifest or service worker has been added.</p><div class="icons"><figure><img src="icons/before.ico" width="32" height="32" alt="Previous browser favicon"><figcaption>Previous favicon · 32px</figcaption></figure><figure><img src="icons/favicon.svg" width="16" height="16" alt="F1 favicon at 16 pixels"><figcaption>F1 · 16px</figcaption></figure><figure><img src="icons/favicon.svg" width="32" height="32" alt="F1 favicon at 32 pixels"><figcaption>F1 · 32px</figcaption></figure><figure><img src="icons/phone.png" width="180" height="180" alt="B1 cream on velvet phone icon"><figcaption>B1 · 180px source</figcaption></figure></div></section>
<footer>Alignment preview approved; final PR delivery authorized. <a href="README.md">Capture method and verification notes</a>.</footer>
</main><script>
const width=document.querySelector('#width'),state=document.querySelector('#state');const query=new URLSearchParams(location.search);if(query.has('screen')&&[...state.options].some(o=>o.value===query.get('screen')))state.value=query.get('screen');if(query.has('width')&&[...width.options].some(o=>o.value===query.get('width')))width.value=query.get('width');function filter(){let count=0;document.querySelectorAll('article').forEach(card=>{const show=(width.value==='all'||card.dataset.width===width.value)&&(state.value==='all'||card.dataset.state===state.value);card.classList.toggle('hidden',!show);if(show)count++});document.querySelector('#count').textContent=count+(count===1?' comparison':' comparisons')}width.addEventListener('change',filter);state.addEventListener('change',filter);filter();
</script></body></html>\n`);
