export const matchingConsentStrings = {
  en: {
    title: 'Matching preferences', info: 'How we use these details', close: 'Close',
    purpose: 'Your gender and dating preferences help us suggest compatible people in the same venue and show your profile to them. This matching cannot work without your agreement.',
    retention: 'You can withdraw in your profile at any time. We then remove your gender and dating preferences and stop new suggestions and likes. Existing conversations stay active until the night ends, when they are deleted.',
    draft: 'Test registration only. The operator details, full privacy information and consent-record retention are being finalized before public registration opens.',
    privacy: 'Privacy information', contact: 'Privacy questions',
    required: 'Please agree to the use of your gender and dating preferences to enable matching.',
    active: 'Your agreement is active.', inactive: 'Matching is off. Your gender and dating preferences are not saved. Existing conversations remain available until the night ends.',
    withdraw: 'Withdraw my agreement', confirm: 'Turn off matching?',
    effect: 'Your gender and dating preferences will be removed. You will stop seeing suggestions and receiving new likes. Your existing conversations stay active until the night ends. You can agree again later; any current preference-change waiting period still applies.',
    cancel: 'Keep my agreement', saving: 'Saving…', loading: 'Checking your agreement…',
    retry: 'Check again', error: 'We could not confirm your agreement status. Check again before continuing.',
    stale: 'Your agreement changed in another session. Review the current state before continuing.',
    grant: 'Agree and enable matching', cooldown: 'You can enable matching with new preferences after',
    choose: 'Choose your gender and preferences again, then confirm your agreement.',
  },
  fr: {
    title: 'Préférences de rencontre', info: 'Comment ces informations sont utilisées', close: 'Fermer',
    purpose: 'Ton genre et tes préférences de rencontre nous permettent de te proposer des personnes compatibles dans le même lieu et de leur montrer ton profil. Ce matching ne peut pas fonctionner sans ton accord.',
    retention: 'Tu peux retirer ton accord dans ton profil à tout moment. Nous supprimons alors ton genre et tes préférences de rencontre et arrêtons les nouvelles suggestions et les nouveaux likes. Les conversations existantes restent actives jusqu’à la fin de la soirée, puis sont supprimées.',
    draft: 'Inscription réservée aux tests. L’identité du responsable, les informations complètes de confidentialité et la durée de conservation des preuves de consentement sont en cours de finalisation avant l’ouverture au public.',
    privacy: 'Informations de confidentialité', contact: 'Questions sur la confidentialité',
    required: 'Accepte l’utilisation de ton genre et de tes préférences de rencontre pour activer le matching.',
    active: 'Ton accord est actif.', inactive: 'Le matching est désactivé. Ton genre et tes préférences de rencontre ne sont pas enregistrés. Tes conversations existantes restent disponibles jusqu’à la fin de la soirée.',
    withdraw: 'Retirer mon accord', confirm: 'Désactiver le matching ?',
    effect: 'Ton genre et tes préférences de rencontre seront supprimés. Tu ne verras plus de suggestions et ne recevras plus de nouveaux likes. Tes conversations existantes resteront actives jusqu’à la fin de la soirée. Tu pourras donner à nouveau ton accord ; le délai de modification des préférences en cours restera applicable.',
    cancel: 'Garder mon accord', saving: 'Enregistrement…', loading: 'Vérification de ton accord…',
    retry: 'Vérifier à nouveau', error: 'Impossible de confirmer l’état de ton accord. Vérifie à nouveau avant de continuer.',
    stale: 'Ton accord a changé dans une autre session. Vérifie son état actuel avant de continuer.',
    grant: 'Accepter et activer le matching', cooldown: 'Tu pourras activer le matching avec de nouvelles préférences après le',
    choose: 'Choisis à nouveau ton genre et tes préférences, puis confirme ton accord.',
  },
  es: {
    title: 'Preferencias de citas', info: 'Cómo usamos estos datos', close: 'Cerrar',
    purpose: 'Tu género y tus preferencias de citas nos permiten sugerirte personas compatibles en el mismo local y mostrarles tu perfil. Este matching no puede funcionar sin tu acuerdo.',
    retention: 'Puedes retirar tu acuerdo desde tu perfil en cualquier momento. Eliminaremos tu género y tus preferencias de citas y detendremos las nuevas sugerencias y los nuevos likes. Las conversaciones existentes seguirán activas hasta el final de la noche, cuando se eliminarán.',
    draft: 'Registro solo para pruebas. Los datos del responsable, la información completa de privacidad y el plazo de conservación de las pruebas de consentimiento se están preparando antes de abrir el registro al público.',
    privacy: 'Información de privacidad', contact: 'Consultas sobre privacidad',
    required: 'Acepta el uso de tu género y tus preferencias de citas para activar el matching.',
    active: 'Tu acuerdo está activo.', inactive: 'El matching está desactivado. Tu género y tus preferencias de citas no están guardados. Tus conversaciones existentes siguen disponibles hasta el final de la noche.',
    withdraw: 'Retirar mi acuerdo', confirm: '¿Desactivar el matching?',
    effect: 'Se eliminarán tu género y tus preferencias de citas. Dejarás de ver sugerencias y de recibir nuevos likes. Tus conversaciones existentes seguirán activas hasta el final de la noche. Podrás dar tu acuerdo de nuevo; seguirá aplicándose el plazo de espera vigente para cambiar las preferencias.',
    cancel: 'Mantener mi acuerdo', saving: 'Guardando…', loading: 'Comprobando tu acuerdo…',
    retry: 'Comprobar de nuevo', error: 'No hemos podido confirmar el estado de tu acuerdo. Compruébalo de nuevo antes de continuar.',
    stale: 'Tu acuerdo ha cambiado en otra sesión. Revisa su estado actual antes de continuar.',
    grant: 'Aceptar y activar el matching', cooldown: 'Podrás activar el matching con nuevas preferencias después del',
    choose: 'Elige de nuevo tu género y tus preferencias y confirma tu acuerdo.',
  },
} as const;
