export const profileEditStrings = {
  en: {
    bio: 'Bio', preferences: 'Gender and preferences', saveBio: 'Save my bio', bioSaved: 'Bio saved.',
    save: 'Save my preferences', saved: 'Preferences saved.', loading: 'Checking your preferences…',
    saving: 'Saving…', confirm: 'Save these preferences?', cancel: 'Keep editing',
    warning: 'Changing your gender or adding a preference starts a 12-hour wait before another such change. You can still remove preferences, keeping at least one choice. To pause your visibility, use invisible mode in the venue.',
    indicative: 'Next change available around', until: 'Gender changes and new preferences available from',
    narrowing: 'You can still remove preferences. Keep at least one choice, or use invisible mode in the venue.',
    conflict: 'Your saved preferences changed in another session. Your draft is still here. Load the saved values before editing again.',
    adopt: 'Load saved preferences', retry: 'Check again',
    error: 'Could not verify your preferences. Your draft is still here. Check again before saving.',
    cooldown: 'This change is not available yet. You can still remove preferences.',
  },
  fr: {
    bio: 'Bio', preferences: 'Genre et préférences', saveBio: 'Enregistrer ma bio', bioSaved: 'Bio enregistrée.',
    save: 'Enregistrer mes préférences', saved: 'Préférences enregistrées.', loading: 'Vérification de tes préférences…',
    saving: 'Enregistrement…', confirm: 'Enregistrer ces préférences ?', cancel: 'Continuer à modifier',
    warning: 'Changer de genre ou ajouter une préférence déclenche un délai de 12 h avant un nouveau changement de ce type. Tu peux toujours retirer des préférences en gardant au moins un choix. Pour suspendre ta visibilité, utilise le mode invisible dans le lieu.',
    indicative: 'Prochain changement possible vers', until: 'Changement de genre et ajout de préférences possibles à partir du',
    narrowing: 'Tu peux toujours retirer des préférences. Garde au moins un choix, ou utilise le mode invisible dans le lieu.',
    conflict: 'Tes préférences enregistrées ont changé dans une autre session. Ton brouillon est conservé. Reprends les valeurs enregistrées avant de modifier à nouveau.',
    adopt: 'Reprendre les préférences enregistrées', retry: 'Vérifier à nouveau',
    error: 'Impossible de vérifier tes préférences. Ton brouillon est conservé. Vérifie à nouveau avant d’enregistrer.',
    cooldown: 'Ce changement n’est pas encore disponible. Tu peux toujours retirer des préférences.',
  },
  es: {
    bio: 'Bio', preferences: 'Género y preferencias', saveBio: 'Guardar mi bio', bioSaved: 'Bio guardada.',
    save: 'Guardar mis preferencias', saved: 'Preferencias guardadas.', loading: 'Comprobando tus preferencias…',
    saving: 'Guardando…', confirm: '¿Guardar estas preferencias?', cancel: 'Seguir editando',
    warning: 'Cambiar de género o añadir una preferencia inicia una espera de 12 horas antes de otro cambio de este tipo. Puedes seguir quitando preferencias, manteniendo al menos una opción. Para pausar tu visibilidad, usa el modo invisible en el local.',
    indicative: 'Próximo cambio disponible aproximadamente a las', until: 'Cambio de género y nuevas preferencias disponibles a partir de',
    narrowing: 'Puedes seguir quitando preferencias. Mantén al menos una opción, o usa el modo invisible en el local.',
    conflict: 'Tus preferencias guardadas cambiaron en otra sesión. Tu borrador sigue aquí. Carga los valores guardados antes de volver a editar.',
    adopt: 'Cargar preferencias guardadas', retry: 'Comprobar de nuevo',
    error: 'No se pudieron verificar tus preferencias. Tu borrador sigue aquí. Comprueba de nuevo antes de guardar.',
    cooldown: 'Este cambio aún no está disponible. Puedes seguir quitando preferencias.',
  },
};
