export const profileEditStrings = {
  en: {
    bio: 'Bio', preferences: 'Gender and preferences', saveBio: 'Save my bio', bioSaved: 'Bio saved.',
    save: 'Save my preferences', saved: 'Preferences saved.', loading: 'Checking your preferences…',
    saving: 'Saving…', confirm: 'Save these preferences?', cancel: 'Keep editing',
    warning: 'You won’t be able to change your gender or add preferences for 12 hours. You can still remove preferences.',
    until: 'Changes limited until',
    narrowing: 'You can still remove preferences.',
    conflict: 'Your saved preferences changed in another session. Your draft is still here. Load the saved values before editing again.',
    adopt: 'Load saved preferences', retry: 'Check again',
    error: 'Could not verify your preferences. Your draft is still here. Check again before saving.',
    cooldown: 'This change is not available yet. You can still remove preferences.',
  },
  fr: {
    bio: 'Bio', preferences: 'Genre et préférences', saveBio: 'Enregistrer ma bio', bioSaved: 'Bio enregistrée.',
    save: 'Enregistrer mes préférences', saved: 'Préférences enregistrées.', loading: 'Vérification de tes préférences…',
    saving: 'Enregistrement…', confirm: 'Enregistrer ces préférences ?', cancel: 'Continuer à modifier',
    warning: 'Tu ne pourras plus changer ton genre ni ajouter de préférences pendant 12 h. Tu pourras toujours en retirer.',
    until: 'Modifications limitées jusqu’au',
    narrowing: 'Tu peux toujours retirer des préférences.',
    conflict: 'Tes préférences enregistrées ont changé dans une autre session. Ton brouillon est conservé. Reprends les valeurs enregistrées avant de modifier à nouveau.',
    adopt: 'Reprendre les préférences enregistrées', retry: 'Vérifier à nouveau',
    error: 'Impossible de vérifier tes préférences. Ton brouillon est conservé. Vérifie à nouveau avant d’enregistrer.',
    cooldown: 'Ce changement n’est pas encore disponible. Tu peux toujours retirer des préférences.',
  },
  es: {
    bio: 'Bio', preferences: 'Género y preferencias', saveBio: 'Guardar mi bio', bioSaved: 'Bio guardada.',
    save: 'Guardar mis preferencias', saved: 'Preferencias guardadas.', loading: 'Comprobando tus preferencias…',
    saving: 'Guardando…', confirm: '¿Guardar estas preferencias?', cancel: 'Seguir editando',
    warning: 'No podrás cambiar tu género ni añadir preferencias durante 12 horas. Podrás seguir quitando preferencias.',
    until: 'Cambios limitados hasta',
    narrowing: 'Puedes seguir quitando preferencias.',
    conflict: 'Tus preferencias guardadas cambiaron en otra sesión. Tu borrador sigue aquí. Carga los valores guardados antes de volver a editar.',
    adopt: 'Cargar preferencias guardadas', retry: 'Comprobar de nuevo',
    error: 'No se pudieron verificar tus preferencias. Tu borrador sigue aquí. Comprueba de nuevo antes de guardar.',
    cooldown: 'Este cambio aún no está disponible. Puedes seguir quitando preferencias.',
  },
};
