-- Isolated pre-photo-moderation substrate shared by SQL authorization tests.
create role anon; create role authenticated; create role service_role bypassrls;
create schema auth; create schema private; create schema storage; create schema vault; create schema net; create schema cron;
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
create table auth.users(id uuid primary key);
create table public.admins(user_id uuid primary key);
create function private.is_admin() returns boolean language sql stable security definer as $$select exists(select 1 from public.admins where user_id=auth.uid())$$;
create table public.profiles(id uuid primary key references auth.users(id) on delete cascade, first_name text not null, photo_url text not null, bio text, gender text, interested_in text[],created_at timestamptz default now(),updated_at timestamptz default now());
create table public.profile_private(id uuid primary key references public.profiles(id) on delete cascade,adult_confirmed_at timestamptz);
create table public.venues(id uuid primary key,is_live boolean default true,profile_preview_enabled boolean default false);
create table public.venue_nights(id uuid primary key,venue_id uuid references public.venues(id),status text default 'live',terminal_at timestamptz,closes_at timestamptz default now()+interval '1 day');
create table public.presence(id uuid primary key default gen_random_uuid(),profile_id uuid references public.profiles(id),venue_id uuid,venue_night_id uuid,is_visible boolean default true,left_at timestamptz);
create table public.matches(id uuid primary key default gen_random_uuid(),profile_a uuid,profile_b uuid,venue_night_id uuid,expires_at timestamptz default now()+interval '1 day');
create table public.likes(id uuid primary key default gen_random_uuid(),liker_id uuid,liked_id uuid,venue_night_id uuid);
create function private.visible_profile_ids() returns setof uuid language sql stable as $$select auth.uid()$$;
create table public.blocks(blocker_id uuid,blocked_id uuid);
create table public.reports(reported_id uuid);
create table public.venue_night_public_state(venue_night_id uuid primary key,updated_at timestamptz default now());
create function private.is_open_venue_night(uuid) returns boolean language sql as $$select exists(select 1 from public.venue_nights where id=$1 and status in ('live','waiting') and terminal_at is null and closes_at>now())$$;
create function private.is_live_venue_night(uuid) returns boolean language sql as $$select exists(select 1 from public.venue_nights where id=$1 and status='live' and terminal_at is null and closes_at>now())$$;
create function private.refresh_venue_night_public_state(uuid) returns void language sql as $$insert into public.venue_night_public_state values($1,now()) on conflict(venue_night_id) do update set updated_at=now()$$;
create table storage.buckets(id text primary key,public boolean); insert into storage.buckets values('profile-photos',true);
create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text,name text,metadata jsonb,created_at timestamptz default now());
create table vault.decrypted_secrets(name text,decrypted_secret text);
create function cron.schedule(text,text,text) returns bigint language sql as $$select 1::bigint$$;
create publication supabase_realtime;
alter table public.profiles enable row level security;
alter table public.presence enable row level security;
alter table storage.objects enable row level security;
create policy profiles_update_own on public.profiles for update to authenticated using(id=auth.uid()) with check(id=auth.uid());
create policy presence_read on public.presence for select to authenticated using(true);
grant usage on schema public,private,auth,storage to authenticated;
grant select,insert,update on public.profiles to authenticated;
grant select on public.presence,storage.objects to authenticated;
grant insert,select on public.likes to authenticated;
